### PR TITLE
Fix font color of logo

### PR DESCRIPTION
**Pull request by studenton**
The font color of the logo text and the background both are black. Due to this, the logo gets hidden and is only revealed on hover. I changed the text to a lighter color to fix it.

### CODE REVIEW

**Comment by studenton** [comment]
image

**Comment by studenton** [comment]
@samundra @rhoit Can you please review this PR?

**Comment by samundra** [comment]
looks good :) also add on hover.

```css
a#logo:hover { color: #fff; }
```

👍

**Comment by samundra** [comment]
I am closing this PR. I have included this PR on https://github.com/foss-np/foss-np.github.com/pull/14. If for some reason the PR is not merged then we can always reopen this PR.

**Comment by rhoit** [comment]
nice job guys 👍

**Pull request closed without merging**
